<script src="<?php echo base_url('assets/front/'); ?>lib/jquery/jquery.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/jquery/jquery-migrate.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/popper/popper.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/easing/easing.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/counterup/jquery.waypoints.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/counterup/jquery.counterup.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/owlcarousel/owl.carousel.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/lightbox/js/lightbox.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>lib/typed/typed.min.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>contactform/contactform.js"></script>
<script src="<?php echo base_url('assets/front/'); ?>js/main.js"></script>
<script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
<script src="<?php echo base_url('assets/front/'); ?>js/custom.js"></script>
